# Generated by Django 2.0.3 on 2018-03-14 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20180312_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pub_author',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 14, 16, 35, 690087), verbose_name='date added'),
        ),
    ]
