# Generated by Django 2.0.3 on 2018-03-14 20:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_auto_20180312_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 14, 20, 38, 41, 995147), verbose_name='date added'),
        ),
    ]
