# Generated by Django 2.0.3 on 2018-03-15 11:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180314_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pub_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 15, 13, 51, 44, 285877), verbose_name='date added'),
        ),
    ]
