# Generated by Django 2.0.3 on 2018-03-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20180314_2038'),
        ('notes', '0005_auto_20180315_1351'),
    ]

    operations = [
    ]
