# Generated by Django 2.0.3 on 2018-03-20 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_merge_20180315_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Uncategorized', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.AlterField(
            model_name='note',
            name='note_text',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default='2018-03-20 09:49', verbose_name='date added'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Category'),
        ),
    ]
